#!/bin/bash

if [[ -z "$APPDIR" ]]; then
    export APPDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
fi
export PATH="$APPDIR/usr/bin:$PATH"

if [[ -z "$@" ]]; then
    curv -le new.curv
else
    curv $@
fi